### ISSUE TITLE
Latest working version for the notebooks

### ISSUE THREAD

**Issue by AdrienCorenflos** [thiery-lab/data-assimilation#1]
Hi @matt-graham  @alekk ,

I'm trying to run your code while reading your paper on local filters but it seems like your [cleanup commit](https://github.com/thiery-lab/data-assimilation/commit/be8bf315c635cdb50b9d553755019802a6f5bfe2) broke the notebooks using the PoU classes. What's the latest working version for the notebooks (or alternatively, maybe you have some updated ones that you could upload?)

Thanks

Adrien

**Comment by matt-graham** [comment]
Hi @AdrienCorenflos,

Thanks for pointing this out. I will take a look at this and try update the notebooks / package to try get things working again. Sorry for having being careless and broke things in the first place :sweat_smile:! I'm going to be a bit busy for the next couple of days but will try get this fixed by the end of the week.

Cheers,
Matt

**Comment by AdrienCorenflos** [comment]
Thanks Matt

**Comment by matt-graham** [comment]
It took a little longer than I originally expected (!) but all the notebooks are now updated to be working and the package code has been generally cleaned up to make it a bit more intuitive to use.

**Comment by AdrienCorenflos** [comment]
Thanks a lot, super helpful!

Le mer. 29 juil. 2020 à 01:28, Matt Graham <notifications@github.com> a
écrit :
